
input newUser{
		name:String!
}

type File {
  "ファイルのパス"
  path:String!
  "firebaseのURL"
  url:String!
}

type Source{
  uid:ID!
  projectName:String!
  files:[File!]
}

"ファイルのリクエスト"
input reqFile{
  uid:ID!
  project:String!
}

type User {
  id: ID!
  name: String!
  email: String
}

type Query {
  getFIle(req:reqFile!):[File!]
  numberSix: Int! 
  numberSeven: Int! 
}

type Mutation {
  addStudent(newStudent:newStudent):Student
  "ユーザのサインアップ"
  signUpedUser(newUser:newUser!): User!
  "ソースコードのアップロード"
  sourceUpload(source:Source!):String!
}

type Student{
		name:String!
		school:String!
}

input newStudent{
		name:String!
		school:String!
}

