scalar Upload

input newUser{
		name:String!
}
type File {
    filename: String!
    mimetype: String!
    encoding: String!
}
type Source{
  uid:ID!
  projectName:String!
  urls:[String!]
}
type User {
  id: ID!
  name: String!
  email: String
}

type Query {
  numberSix: Int! 
  numberSeven: Int! 
}

type Mutation {
  addStudent(newStudent:newStudent):Student
	singleUpload(file: Upload!): File!
  signUpedUser(newUser:newUser!): User!
  sourceUpload(source:Source!):Source!
}

type Student{
		name:String!
		school:String!
}

input newStudent{
		name:String!
		school:String!
}

